### ISSUE TITLE
questions about datasets and test performance

### ISSUE THREAD

**Issue by warmingkkk** [leofansq/SpiderMesh#1]
Dear Author:

Thank you very much for your open source code. I encountered some problems when reproducing your code, as follows:

1. Your MFNet data set preprocessed by RTFNet shows no permission to download (so I used the original MFNet data set).

2. The best performance I tested after using your train.py is 55.77.

3. After I tested the weight of your resnet152, the result showed that it was only 55.86, which is much lower than the 57.9 in your paper.

Can you enlighten me? Thank you so much!

**Comment by leofansq** [comment]
We have not met the mentioned performance issues. For convenience, the dataset preprocessed by RTFNet is uploaded to [Download](https://pan.baidu.com/s/1mCIAv2qU5TwIfgDFtAR08g):5ah9. The corresponding link in README is updated.

**Comment by leofansq** [comment]
BTW，I noticed that the original [link](http://nas.ram-lab.com:5000/sharing/CfukComo1) of RTFNet is accessible now.

**Comment by warmingkkk** [comment]
Dear author,

Thank you for your reply. After I downloaded the data set you gave, I found that it is the same as the one I used. I am sorry that

my previous question was wrong, but I am still training with the data set you gave, and the results have not yet come out.  I 

originally thought it was a problem with the data set, but it may not seem to be the case. Let me talk about the configuration i 

used: epoch is 200, batch_size is 6, I have not modified it, i used an a100 gpu for training, but there is still some gap in 

performance. I will try the effect of training on pst900 later.

**Comment by leofansq** [comment]
How about the performance of our uploaded checkpoint? It has been evaluated again, and here is the ouput.
<img width="648" alt="image" src="https://github.com/leofansq/SpiderMesh/assets/30174895/c1ed1527-1dbb-4bd3-8fa9-76df88447086">

**Comment by warmingkkk** [comment]
Yes, but the results I reproduced are not very good, so I feel very confused.
![image](https://github.com/leofansq/SpiderMesh/assets/47290788/ca328a15-2b1a-4aed-9f18-f7d14cca49b9)

This is the result I reproduced:
![image](https://github.com/leofansq/SpiderMesh/assets/47290788/28ef981e-d47e-4c30-804d-9dc17af3062c)

**Comment by warmingkkk** [comment]
Thanks for your help,the training performance now reaches 57.16.
